name: Test And Release

on:
  push:

jobs:
  # -------- Test job -------- #
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Test
        run: go test -v ./...

  # -------- Release job -------- #
  release:
    runs-on: ubuntu-latest
    # Runs only if the event is a tag push.
    # Tag name must start with "v"
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
